config system global
    set private-data-encryption enable
end
config system global
    set autorun-log-fsck enable
    set revision-backup-on-logout enable
    set gui-cdn-usage enable
    set admin-lockout-duration 600
    set cli-audit-log enable
    set admin-telnet disable
    set strong-crypto enable
    set dh-params 8192
    set ssl-static-key-ciphers disable
    set admintimeout 10
    set gui-fortigate-cloud-sandbox enable
    set admin-reset-button disable
end
config system settings
    set internet-service-database-cache enable
end
config system auto-install
    set auto-install-config disable
    set auto-install-image disable
end
config system fortiguard
    set subscribe-update-notification enable
    set persistent-connection disable
end
config system ha
    set session-pickup enable
    set session-pickup-connectionless enable
    set session-pickup-expectation enable
    set memory-based-failover enable
    set memory-failover-threshold 86
    set memory-failover-flip-timeout 60
    set ssd-failover enable
    set ha-uptime-diff-margin 60
end
config system ha-monitor
    set monitor-vlan enable
end
config log setting
    set fwpolicy-implicit-log enable
    set local-in-allow enable
    set local-in-deny-unicast enable
    set local-in-deny-broadcast enable
    set local-out enable
    set extended-log enable
    set extended-utm-log enable
    set resolve-ip enable
    set resolve-port enable
    set rest-api-set enable
    set rest-api-get enable
    set zone-name enable
end
config log memory filter
    set local-traffic enable
end
config log disk setting
    set status enable
    set maximum-log-age 0
end
config antivirus settings
    set machine-learning-detection enable
end
